const fs = require('fs');

// Read env without dotenv
const envFile = fs.readFileSync('.env.local', 'utf8');
const supabaseUrl = envFile.match(/NEXT_PUBLIC_SUPABASE_URL=(.*)/)[1].trim();
const supabaseKey = envFile.match(/NEXT_PUBLIC_SUPABASE_ANON_KEY=(.*)/)[1].trim();

const questions = [
  // Constitutional Law (10)
  { category: 'Constitutional Law', question_text: 'What is the doctrine of judicial review and how does it empower courts to examine the constitutionality of legislation?', existing_answer: 'Judicial review is the power of courts to examine whether laws passed by the legislature or actions taken by the executive branch conform to the constitution. Originating from Marbury v. Madison (1803), it allows courts to strike down legislation found unconstitutional, thereby upholding the supremacy of the constitution and maintaining the balance of power among the three branches of government.' },
  { category: 'Constitutional Law', question_text: 'Explain the concept of separation of powers and its importance in a democratic state.', existing_answer: 'Separation of powers is a constitutional principle that distributes governmental authority among three distinct branches: the legislature (which makes laws), the executive (which enforces laws), and the judiciary (which interprets laws). This division prevents the concentration of power in one branch, protects individual liberties, and creates a system of checks and balances ensuring accountability and preventing tyranny.' },
  { category: 'Constitutional Law', question_text: 'What are fundamental rights and how are they protected under constitutional law?', existing_answer: 'Fundamental rights are basic human rights enshrined in the constitution that are considered essential for individual dignity and liberty. They are protected by being justiciable, meaning citizens can approach courts if these rights are violated. Constitutional provisions typically include rights to equality, freedom of expression, religion, and life. Courts act as guardians to prevent state infringement on these protected rights.' },
  { category: 'Constitutional Law', question_text: 'Describe the doctrine of basic structure and its significance in constitutional interpretation.', existing_answer: 'The basic structure doctrine holds that a constitution has certain fundamental features that cannot be altered or destroyed through amendments. Established in Kesavananda Bharati v. State of Kerala, it protects the essential framework of the constitution including judicial independence, separation of powers, and fundamental rights. Amendments that damage this basic structure are held unconstitutional.' },
  { category: 'Constitutional Law', question_text: 'What is the principle of constitutional supremacy and how does it differ from parliamentary supremacy?', existing_answer: 'Constitutional supremacy holds that the constitution is the supreme law of the land and all other laws must conform to it. Parliamentary supremacy, in contrast, holds that parliament can enact any law it chooses without limitation. In constitutional supremacy systems, courts can invalidate laws; in parliamentary supremacy systems like the UK traditionally, courts cannot override Parliament. Constitutional supremacy better protects individual rights.' },
  { category: 'Constitutional Law', question_text: 'Explain the role and scope of fundamental duties in constitutional law.', existing_answer: 'Fundamental duties are obligations of citizens toward the state and society, complementing fundamental rights. They represent moral obligations that citizens should uphold, including respecting the constitution, protecting public property, promoting harmony, and defending the country. While generally non-justiciable, they serve as benchmarks for legislation and courts may consider them when resolving conflicts between rights and state interests.' },
  { category: 'Constitutional Law', question_text: 'How does the constitution balance individual rights with state interests in times of emergency?', existing_answer: 'Constitutions typically include emergency provisions allowing temporary suspension or curtailment of certain rights when national security, public order, or financial stability is threatened. Emergency powers must be declared through defined procedures, be subject to legislative oversight, and be time-limited. Courts maintain a limited review role, ensuring emergencies are not used as pretexts to permanently erode constitutional guarantees.' },
  { category: 'Constitutional Law', question_text: 'What is federalism and how does it affect the distribution of legislative powers?', existing_answer: 'Federalism is a system of government where powers are constitutionally divided between a central government and regional governments (states/provinces). Legislative powers are typically distributed through schedules or lists—federal, state, and concurrent. The central government handles national matters like defense, while states handle local matters. In areas of conflict, federal law usually prevails through the doctrine of federal supremacy.' },
  { category: 'Constitutional Law', question_text: 'Explain the doctrine of proportionality in constitutional adjudication.', existing_answer: 'Proportionality is a constitutional principle requiring that state measures limiting rights must be appropriate, necessary, and proportionate to the legitimate aim pursued. Courts assess whether the limitation is rationally connected to its objective, whether there are less restrictive alternatives, and whether the benefits outweigh the harms. It prevents excessive government action even when pursuing legitimate goals.' },
  { category: 'Constitutional Law', question_text: 'What is constitutional interpretation and what are the major schools of interpretive thought?', existing_answer: 'Constitutional interpretation is the process of determining the meaning and application of constitutional provisions. Major schools include: Originalism (interpreting the constitution according to its original meaning or intent), Textualism (focusing on the literal text), Living Constitutionalism (adapting the constitution to contemporary circumstances), and Structuralism (deriving meaning from the constitutional structure). Each approach leads to different outcomes in constitutional adjudication.' },

  // Criminal Law (10)
  { category: 'Criminal Law', question_text: 'Explain the concept of mens rea and its role in establishing criminal liability.', existing_answer: 'Mens rea, meaning "guilty mind," refers to the mental element required for criminal liability. It encompasses intention, knowledge, recklessness, and negligence. For most crimes, the prosecution must prove that the accused acted with the requisite mental state. The principle ensures that individuals are not held criminally responsible for purely accidental acts, distinguishing morally blameworthy conduct from innocent mistakes.' },
  { category: 'Criminal Law', question_text: 'What is actus reus and how does it combine with mens rea to establish a criminal offense?', existing_answer: 'Actus reus refers to the physical element of a crime—the guilty act or omission. Combined with mens rea, it forms the foundation of criminal liability under the principle "actus non facit reum nisi mens sit rea" (an act does not make a person guilty unless the mind is also guilty). Both elements must concur at the time of the offense; the act must be voluntary and caused by the defendant.' },
  { category: 'Criminal Law', question_text: 'Describe the doctrine of strict liability in criminal law and provide examples.', existing_answer: 'Strict liability offenses impose criminal responsibility without requiring proof of mens rea. The prosecution only needs to prove the actus reus. These typically apply in regulatory contexts: traffic violations, food safety breaches, and environmental offenses. Rationale includes protecting public safety, ease of prosecution, and deterrence. Critics argue it conflicts with the fundamental presumption of innocence and moral culpability principles.' },
  { category: 'Criminal Law', question_text: 'What is the defense of insanity in criminal law? Explain the M\'Naghten Rules.', existing_answer: 'The insanity defense excuses criminal liability when a mental disorder prevented the accused from understanding the nature or wrongfulness of their act. The M\'Naghten Rules (1843) establish the test: the accused must prove that at the time of the offense, they were suffering from such a defect of reason from disease of the mind that they did not know the nature and quality of the act, or did not know it was wrong.' },
  { category: 'Criminal Law', question_text: 'Explain the doctrine of provocation as a defense in homicide cases.', existing_answer: 'Provocation is a partial defense that reduces murder to manslaughter when the accused lost self-control due to a provoking act. Traditional requirements included: sudden provocation, actual loss of control, and a reasonable person test. Modern formulations often replace "sudden" with a slow-burn response and assess whether a person of ordinary temperament might have reacted similarly. It acknowledges human emotional frailty without fully excusing the act.' },
  { category: 'Criminal Law', question_text: 'What is the principle of double jeopardy and how does it protect accused persons?', existing_answer: 'Double jeopardy is a constitutional protection preventing a person from being tried twice for the same offense after acquittal or conviction. The plea of autrefois acquit (formerly acquitted) or autrefois convict (formerly convicted) bars subsequent prosecution. It protects individuals from harassment by successive prosecutions, provides finality to judgments, and prevents the state from using multiple trials to secure a conviction.' },
  { category: 'Criminal Law', question_text: 'Describe the standard of proof in criminal cases and why it differs from civil cases.', existing_answer: 'In criminal cases, guilt must be proven "beyond a reasonable doubt"—the highest legal standard—reflecting the serious consequences of criminal conviction including loss of liberty. In civil cases, the standard is "balance of probabilities" or "preponderance of evidence." The higher criminal standard protects the presumption of innocence and recognizes that it is better that guilty persons escape than innocent persons be wrongly convicted.' },
  { category: 'Criminal Law', question_text: 'What are the elements of attempt as a criminal offense?', existing_answer: 'Criminal attempt consists of: (1) an intention to commit a specific crime, (2) an act that goes beyond mere preparation toward the commission of the offense. The "proximity" test measures how close the act came to completion. Attempt is punishable even if the crime was not completed, recognizing the offender\'s culpability and deterring dangerous conduct. The sentence for attempt is typically less than for the completed offense.' },
  { category: 'Criminal Law', question_text: 'Explain the concept of joint criminal enterprise and how liability is attributed in group crimes.', existing_answer: 'Joint criminal enterprise (JCE) holds all participants in a common criminal purpose liable for acts committed in furtherance of that purpose, even if not personally performed. Three forms exist: basic JCE (shared intent), systemic JCE (participants in a system), and extended JCE (acts beyond the common plan but foreseeable). It addresses the collective nature of criminal activity and prevents participants from avoiding liability by pointing to others.' },
  { category: 'Criminal Law', question_text: 'What is the role of circumstantial evidence in criminal prosecutions?', existing_answer: 'Circumstantial evidence establishes facts from which guilt may be inferred rather than directly proving the offense. Courts can convict solely on circumstantial evidence if it is inconsistent with any reasonable hypothesis of innocence. This requires the chain of circumstances to be complete, consistent with guilt, and inconsistent with innocence. Circumstantial evidence, carefully analyzed, can be as compelling as direct eyewitness testimony.' },

  // Civil Law (10)
  { category: 'Civil Law', question_text: 'What is the law of contract and what are its essential elements?', existing_answer: 'Contract law governs legally binding agreements between parties. Essential elements include: (1) offer—a clear proposal to contract, (2) acceptance—unequivocal assent to the offer, (3) consideration—something of value exchanged, (4) intention to create legal relations, (5) capacity—parties must be legally competent, and (6) legality—the contract\'s purpose must be lawful. Absence of any element may render the agreement unenforceable.' },
  { category: 'Civil Law', question_text: 'Explain the tort of negligence and its elements.', existing_answer: 'Negligence is a civil wrong arising from breach of a duty of care causing damage. Elements include: (1) duty of care—defendant owed plaintiff a legal duty, (2) breach—defendant failed to meet the standard of a reasonable person, (3) causation—the breach caused the harm (factual and legal causation), and (4) damage—plaintiff suffered actual harm. The neighbor principle from Donoghue v. Stevenson establishes proximity as a basis for duty.' },
  { category: 'Civil Law', question_text: 'What is the doctrine of res ipsa loquitur and when does it apply?', existing_answer: 'Res ipsa loquitur ("the thing speaks for itself") is an evidentiary doctrine in negligence that allows courts to infer negligence from the circumstances of an accident without direct evidence of fault. It applies when: (1) the event is of a kind that ordinarily would not occur without negligence, (2) the defendant had exclusive control of the instrumentality causing harm, and (3) the plaintiff did not contribute to the accident. It shifts the evidential burden to the defendant.' },
  { category: 'Civil Law', question_text: 'Describe the remedies available for breach of contract.', existing_answer: 'Remedies for breach of contract include: (1) Damages—compensatory (expectation and reliance), nominal, liquidated, and punitive; (2) Specific Performance—court order compelling performance, typically for unique goods or land; (3) Injunction—order restraining breach of a negative covenant; (4) Rescission—cancellation restoring parties to pre-contract positions; and (5) Restitution—recovery of unjust enrichment. The primary aim is to place the innocent party in the position they would have been in had the contract been performed.' },
  { category: 'Civil Law', question_text: 'What is vicarious liability and what is its legal basis?', existing_answer: 'Vicarious liability is the principle by which one person is held liable for the tortious acts of another. The most common application is employer liability for employees\' acts during the course of employment. Its basis includes enterprise risk (employers create the risk by employing others), economic efficiency (employers can spread losses through insurance), and deterrence (encouraging employers to prevent employee torts). The relationship and connection to employment are key determinants.' },
  { category: 'Civil Law', question_text: 'Explain the principle of mitigation of damages in civil law.', existing_answer: 'The mitigation principle requires an innocent party to take reasonable steps to reduce their losses following a breach or tort. If they fail to mitigate, damages are reduced by the amount that could have been avoided through reasonable action. The duty is not absolute—only reasonable steps are required. This principle prevents claimants from passively allowing losses to accumulate when they could reasonably reduce them.' },
  { category: 'Civil Law', question_text: 'What is the tort of defamation and what must a claimant prove?', existing_answer: 'Defamation protects reputation from false statements. A claimant must prove: (1) the defendant made a false statement, (2) the statement was published to a third party, (3) the statement referred to the claimant, and (4) the statement caused or is likely to cause serious harm to reputation. Libel is written defamation; slander is spoken. Defenses include truth, honest opinion, and privilege (absolute or qualified).' },
  { category: 'Civil Law', question_text: 'Describe the doctrine of frustration in contract law.', existing_answer: 'Frustration discharges a contract when, after its formation, an unforeseen event makes performance impossible, illegal, or radically different from what was contracted for, through no fault of either party. Examples include destruction of the subject matter, death of a personal service contractor, or supervening illegality. The legal effect is automatic termination, with courts then dealing with consequences such as recovery of payments made.' },
  { category: 'Civil Law', question_text: 'What is the law of unjust enrichment and when does it apply?', existing_answer: 'Unjust enrichment is an equitable principle requiring restitution when one party is enriched at another\'s expense in circumstances the law considers unjust. Requirements include: (1) defendant\'s enrichment, (2) at the claimant\'s expense, (3) in circumstances making enrichment unjust (absence of legal basis). It covers situations like mistaken payments, total failure of consideration, and free acceptance of services. The remedy is restitution, not compensation for loss.' },
  { category: 'Civil Law', question_text: 'Explain the concept of tortious interference with contractual relations.', existing_answer: 'Tortious interference occurs when a third party intentionally induces breach of another\'s contractual rights. Elements include: (1) existence of a valid contract, (2) defendant\'s knowledge of it, (3) intentional and improper interference, (4) breach or disruption, and (5) resulting damage. The tort balances freedom of commerce with protection of existing contractual rights. Defenses include justification and acting in good faith to protect legitimate interests.' },

  // Evidence Law (10)
  { category: 'Evidence Law', question_text: 'What is hearsay evidence and what are the exceptions to the hearsay rule?', existing_answer: 'Hearsay is an out-of-court statement offered to prove the truth of the matter asserted. The rule generally excludes hearsay because the declarant is unavailable for cross-examination. Major exceptions include: dying declarations (statements made believing death was imminent), res gestae (spontaneous statements during events), admissions by parties, business records, and public documents. Exceptions are justified by indicia of reliability that substitute for cross-examination.' },
  { category: 'Evidence Law', question_text: 'Explain the concept of legal professional privilege and its scope.', existing_answer: 'Legal professional privilege (attorney-client privilege) protects confidential communications between lawyers and clients from disclosure in legal proceedings. Legal advice privilege covers all communications for legal advice; litigation privilege covers communications made for existing or anticipated litigation. The privilege belongs to the client, who may waive it. Exceptions include communications made to facilitate crime or fraud. It underpins the right to receive frank legal advice and access to justice.' },
  { category: 'Evidence Law', question_text: 'What is the burden of proof and how does it operate in civil and criminal proceedings?', existing_answer: 'The burden of proof determines who must prove the facts in dispute. The legal burden is the overall obligation to prove a case; the evidential burden is the obligation to produce sufficient evidence for consideration. In criminal trials, the prosecution bears the legal burden to prove guilt beyond reasonable doubt. In civil cases, the claimant bears the burden on balance of probabilities. The burden can shift for specific defenses (e.g., insanity, self-defense).' },
  { category: 'Evidence Law', question_text: 'Describe the admissibility of confessions and the circumstances under which they may be excluded.', existing_answer: 'Confessions are admissible if voluntary and not obtained by oppression, promises, or threats. Courts may exclude confessions that are unreliable or obtained in breach of proper procedures (e.g., denial of legal advice, failure to caution). The judge conducts a voir dire to determine admissibility. Wrongfully obtained confessions threaten both the integrity of the judicial process and the right against self-incrimination.' },
  { category: 'Evidence Law', question_text: 'What is character evidence and when is it admissible in criminal proceedings?', existing_answer: 'Character evidence relates to a person\'s general disposition or reputation. In criminal proceedings, evidence of the accused\'s bad character is generally inadmissible to prove propensity, as it may prejudice the jury. However, it becomes admissible when: the defendant raises their own good character, the evidence is relevant to an issue, it shows a similar fact/pattern, or the accused attacks witnesses\' character. Courts may exclude admissible character evidence if prejudice outweighs probative value.' },
  { category: 'Evidence Law', question_text: 'Explain the doctrine of similar fact evidence and its application.', existing_answer: 'Similar fact evidence (propensity evidence) refers to evidence of prior acts used to show the accused acted similarly on the occasion in question. Admissibility requires that probative value outweighs prejudicial effect. It is most compelling where prior acts show a distinctive pattern (modus operandi) making coincidence implausible. Courts balance its relevance against the risk of unfair prejudice and the danger of reasoning from bad character.' },
  { category: 'Evidence Law', question_text: 'What is expert evidence and what are the criteria for its admissibility?', existing_answer: 'Expert evidence is opinion evidence from a person with specialized knowledge, skill, or experience in a field relevant to issues in the case. Admissibility criteria include: the expert must be qualified, the evidence must be necessary (beyond ordinary understanding), and it must be reliable and based on accepted methodology. Courts are "gatekeepers" preventing unreliable expert evidence from misleading juries. The expert\'s primary duty is to the court, not the party instructing them.' },
  { category: 'Evidence Law', question_text: 'Describe the without prejudice rule and its application in litigation.', existing_answer: 'The without prejudice rule protects genuine settlement negotiations from being admitted as evidence of liability or quantum. Communications marked "without prejudice" made to settle a dispute are inadmissible in subsequent proceedings. The policy rationale is to encourage frank settlement negotiations without fear that admissions will be used against the party. Exceptions include cases where both parties consent to admission, or where the communication is evidence of a concluded agreement.' },
  { category: 'Evidence Law', question_text: 'What is the rule against self-incrimination and how is it protected?', existing_answer: 'The privilege against self-incrimination protects individuals from being compelled to give evidence that may expose them to criminal liability. In criminal proceedings, the accused has the right to silence and cannot be compelled to testify. In civil proceedings, a witness may claim the privilege for specific questions that could incriminate them. Constitutional protections ensure the right is robust; however, inferences may sometimes be drawn from silence in defined circumstances.' },
  { category: 'Evidence Law', question_text: 'Explain the concept of judicial notice and when courts may apply it.', existing_answer: 'Judicial notice allows courts to recognize facts without formal proof when they are so notorious or clearly established that evidence is unnecessary. Two categories exist: (1) facts so universally known that evidence would be absurd (that fire burns), and (2) facts ascertainable by reference to reliable sources (capital cities, dates). Courts must be cautious and allow parties to dispute facts taken on judicial notice to ensure procedural fairness.' },

  // Court Procedures (10)
  { category: 'Court Procedures', question_text: 'What is the principle of natural justice and how does it apply in judicial proceedings?', existing_answer: 'Natural justice encompasses two fundamental procedural principles: audi alteram partem (hear both sides) and nemo judex in causa sua (no one shall be a judge in their own cause). The first requires that all parties have a fair opportunity to present their case; the second requires decision-makers to be impartial. These principles ensure fair hearings, prevent bias, and uphold the integrity of the judicial process.' },
  { category: 'Court Procedures', question_text: 'Describe the stages of a civil lawsuit from filing to judgment.', existing_answer: 'Civil proceedings typically involve: (1) Pre-action protocol compliance and negotiation; (2) Filing a claim/plaint with relevant facts and reliefs; (3) Service on the defendant; (4) Defendant\'s response/written statement; (5) Case management conference; (6) Discovery and exchange of evidence; (7) Interlocutory applications; (8) Trial with examination of witnesses; (9) Final arguments; (10) Judgment; (11) Assessment of damages if liability is established; and (12) Enforcement or appeal.' },
  { category: 'Court Procedures', question_text: 'What is the role of a judge in adversarial versus inquisitorial systems?', existing_answer: 'In adversarial systems (common law), the judge is a neutral arbiter who decides the dispute based on evidence and arguments presented by opposing parties. The parties control the litigation. In inquisitorial systems (civil law), the judge actively investigates, questions witnesses, and gathers evidence. Most modern systems blend elements—judges increasingly intervene to manage cases, ensure fairness, and clarify issues even in adversarial systems.' },
  { category: 'Court Procedures', question_text: 'Explain the concept of res judicata and its effect on subsequent proceedings.', existing_answer: 'Res judicata ("a matter judged") prevents re-litigation of a matter already decided by a competent court. It operates as: (1) Cause of action estoppel—bars re-litigation of the same cause of action between the same parties; (2) Issue estoppel—prevents re-litigation of a specific issue decided in prior proceedings. Requirements include same parties, same issues, and a final judgment on the merits. It promotes finality, judicial economy, and protection from harassment.' },
  { category: 'Court Procedures', question_text: 'What are interlocutory orders and what is their significance in civil proceedings?', existing_answer: 'Interlocutory orders are interim orders made during proceedings before final judgment. They include: injunctions (restraining parties pending trial), security for costs, discovery orders, and summary judgment. The purpose is to preserve the status quo, prevent irreparable harm, or expedite proceedings. Courts weigh whether there is a serious issue to be tried, balance of convenience, and adequacy of damages when granting interlocutory relief.' },
  { category: 'Court Procedures', question_text: 'Describe the procedure for appeal and the grounds on which an appellate court may interfere.', existing_answer: 'Appeals challenge decisions of lower courts for errors of law or fact. Procedure involves filing a memorandum of appeal within prescribed time limits and paying fees. Appellate courts review on grounds including: error of law, perverse findings of fact, procedural irregularities, or miscarriage of justice. Appellate courts are generally reluctant to disturb findings of fact by trial courts who observed witnesses, but will correct errors of legal principle.' },
  { category: 'Court Procedures', question_text: 'What is discovery and how does it operate in civil proceedings?', existing_answer: 'Discovery (disclosure) is the pre-trial process where parties exchange information and evidence relevant to the dispute. It includes: documentary discovery (production of documents), interrogatories (written questions), depositions (oral examination), and requests to admit. The principle is that all relevant evidence should be available to both sides, preventing "trial by ambush." Courts oversee discovery to prevent abuse, protect privileged material, and enforce proportionality.' },
  { category: 'Court Procedures', question_text: 'Explain the concept of contempt of court and its categories.', existing_answer: 'Contempt of court is conduct that disrespects or interferes with the administration of justice. Criminal contempt includes: interference with pending proceedings (sub judice rule), scandalizing the court, and disobeying court orders. Civil contempt involves disobedience of court orders by parties. Punishment includes fines or imprisonment. The rationale is to protect the authority of courts and ensure litigants and the public comply with judicial orders and process.' },
  { category: 'Court Procedures', question_text: 'What is alternative dispute resolution (ADR) and how does it complement the court system?', existing_answer: 'ADR encompasses methods of resolving disputes outside traditional litigation, including negotiation, mediation, conciliation, and arbitration. Mediation uses a neutral third party to facilitate agreement; arbitration involves a binding decision by an arbitrator. Benefits include speed, cost-effectiveness, confidentiality, and preserving relationships. Courts increasingly encourage or require parties to attempt ADR before proceeding to trial, reducing case backlogs while providing flexible dispute resolution.' },
  { category: 'Court Procedures', question_text: 'Describe the powers of courts to award costs and the principles governing cost orders.', existing_answer: 'Courts have discretion to award costs (legal expenses) in civil proceedings. The general rule is "costs follow the event" (the loser pays), but courts may order otherwise considering: conduct of parties, reasonableness of issues pursued, offers of settlement, and complexity. Courts can award full, partial, or no costs. Cost orders serve as deterrents against unmeritorious claims, encourage reasonable conduct, and partially compensate successful parties for litigation expenses.' },

  // Case Law (5)
  { category: 'Case Law', question_text: 'What was the significance of Donoghue v. Stevenson [1932] in the development of negligence law?', existing_answer: 'Donoghue v. Stevenson established the modern law of negligence. A snail found in a ginger beer bottle caused gastroenteritis; there was no contractual relationship between the manufacturer and consumer. Lord Atkin formulated the "neighbour principle"—you must take reasonable care to avoid acts/omissions likely to injure those closely and directly affected by your conduct (neighbors). This created a general duty of care independent of contract, forming the foundation of modern tort law.' },
  { category: 'Case Law', question_text: 'Explain the significance of Rylands v. Fletcher in the law of tort.', existing_answer: 'Rylands v. Fletcher [1868] established strict liability for non-natural use of land. Fletcher\'s contractors built a reservoir on Rylands\' land; water broke through mine shafts into Fletcher\'s mine. The court held that whoever brings onto their land something likely to do mischief if it escapes must keep it at their peril. Blackburn J\'s formulation created strict liability without fault for escaping dangerous things, now confined to extraordinary or non-natural uses of land.' },
  { category: 'Case Law', question_text: 'Describe the principle established in Hedley Byrne v. Heller and its application in negligent misstatement cases.', existing_answer: 'Hedley Byrne & Co v. Heller & Partners [1964] established liability for negligent misstatement causing pure economic loss. Bankers gave a reference without liability disclaimer; the claimant relied on it and suffered loss. The House of Lords held that a duty of care may arise in special relationships where one party voluntarily assumes responsibility for statements knowing the other will rely on them. This created a specific category of liability bridging contract and tort.' },
  { category: 'Case Law', question_text: 'What legal principles were established in Carlill v. Carbolic Smoke Ball Company?', existing_answer: 'Carlill v. Carbolic Smoke Ball Co [1893] established key contract principles. The company advertised £100 reward for anyone using their product who contracted influenza; Carlill used the product and contracted flu. The court held: (1) advertisements can constitute binding offers to the world; (2) performing conditions constitutes acceptance without notification; (3) the company\'s deposit of £1,000 showed intention to create legal relations; (4) the reward was valid consideration. A foundational authority on unilateral contracts.' },
  { category: 'Case Law', question_text: 'Explain the significance of Miller v. Secretary of State for Exiting the European Union for constitutional law.', existing_answer: 'Miller [2017] addressed whether the government could use royal prerogative to trigger Brexit (notify withdrawal from the EU) without parliamentary authorization. The Supreme Court held that parliamentary sovereignty required parliamentary authorization because withdrawal would remove rights conferred by the European Communities Act 1972, which only Parliament could remove. The case reinforced constitutional fundamentals: Parliament is sovereign and the executive cannot alter domestic law through prerogative powers.' },

  // Judicial Ethics (10)
  { category: 'Judicial Ethics', question_text: 'What are the core principles of judicial conduct and how do they uphold public confidence in the judiciary?', existing_answer: 'Core judicial conduct principles include: independence (deciding cases free from external pressure), impartiality (absence of bias or perceived bias), integrity (honesty and moral uprightness), propriety (maintaining dignity on and off bench), equality (treating all parties fairly), and competence (maintaining legal knowledge). These principles, codified in instruments like the Bangalore Principles, are essential to maintaining public trust that cases are decided on law and evidence alone.' },
  { category: 'Judicial Ethics', question_text: 'Explain the concept of judicial independence and why it is essential to the rule of law.', existing_answer: 'Judicial independence means judges decide cases free from influence by the executive, legislature, political parties, or private interests. It encompasses individual independence (personal decisions) and institutional independence (judiciary as a whole). Security of tenure, adequate remuneration, and insulation from political pressure are structural safeguards. Without independence, courts cannot effectively check government power, protect rights, or provide impartial dispute resolution—foundational to the rule of law.' },
  { category: 'Judicial Ethics', question_text: 'What constitutes judicial bias and how should a judge respond to an appearance of bias?', existing_answer: 'Judicial bias includes actual bias (judge has a predisposition toward one outcome) and apparent bias (a fair-minded observer would have a real possibility of bias). Sources include: financial interest, personal relationship, prior involvement, or prejudicial public statements. When bias is reasonably perceived, the judge must disclose it and either disqualify themselves or allow parties to waive the issue. The test is objective: whether a fair-minded, informed observer would apprehend bias.' },
  { category: 'Judicial Ethics', question_text: 'How should judges handle ex parte communications and why are they ethically problematic?', existing_answer: 'Ex parte communications are one-sided communications between a judge and one party without the other present. They violate the principle of impartiality and audi alteram partem. Judges must not receive or engage in ex parte communications about pending cases. If inadvertently received, the judge must promptly notify all parties and provide an opportunity to respond. Breaches undermine the appearance of fairness and erode public confidence in the administration of justice.' },
  { category: 'Judicial Ethics', question_text: 'Describe the ethical obligations of a judge regarding extra-judicial activities.', existing_answer: 'Judges must be cautious in extra-judicial activities to preserve independence and impartiality. They may engage in legal education, scholarship, and civic activities but must avoid: political activity, causes that may embarrass the judiciary, financial activities creating conflicts, and associations that compromise impartiality. Any speaking engagement, publication, or organizational membership should be evaluated for potential prejudice to judicial independence or public perception of impartiality.' },
  { category: 'Judicial Ethics', question_text: 'What is the duty of confidentiality in judicial deliberations and why is it essential?', existing_answer: 'Judicial deliberations must be confidential to protect the integrity of decision-making. Judges must not disclose deliberations, draft opinions, or colleagues\' views in ongoing or concluded cases. Confidentiality enables free expression of views, frank debate, and error correction within the judicial panel before judgment is delivered. It prevents outside influence on deliberations and protects individual judges from pressure based on their tentative positions during the deliberative process.' },
  { category: 'Judicial Ethics', question_text: 'How should a judge maintain dignity and decorum in the courtroom?', existing_answer: 'Judges must maintain the dignity and authority of the court through demeanor, language, and conduct. This includes: treating all parties and advocates with respect regardless of case merit, maintaining composure, refraining from offensive or intemperate language, controlling proceedings firmly but fairly, and ensuring all participants feel heard. Maintaining decorum reinforces the seriousness of the proceedings and the authority of the court as an institution of justice.' },
  { category: 'Judicial Ethics', question_text: 'Explain the obligations of a judge when encountering corruption or misconduct in the judiciary.', existing_answer: 'Judicial ethics require judges to take action upon learning of corruption or serious misconduct by judicial colleagues. This includes reporting to the appropriate judicial oversight body or chief justice. Failure to report may constitute complicity. The obligation must be balanced with procedural fairness (not prejudging) and confidentiality where required. A functional, ethical judiciary depends on its members refusing to tolerate corruption, as judicial misconduct fundamentally undermines the rule of law.' },
  { category: 'Judicial Ethics', question_text: 'What are the principles governing a judge\'s financial conduct and disclosure obligations?', existing_answer: 'Judges must avoid financial interests that could conflict with judicial duties. This includes: avoiding investments in entities whose cases may come before them, not using judicial position for financial gain, making required asset disclosures, and recusing from cases involving financial interests. The Bangalore Principles require propriety even in the appearance of conduct. Transparency through disclosure requirements allows monitoring and maintains public confidence that decisions are not influenced by financial interests.' },
  { category: 'Judicial Ethics', question_text: 'How do judicial ethics codes address the use of social media by judges?', existing_answer: 'Social media use by judges raises concerns about impartiality, dignity, and maintaining the appearance of independence. Judges should avoid: commenting on pending or likely cases, expressing partisan political views, engaging in debates suggesting prejudice on issues likely to appear before them, and conduct that could embarrass the judiciary. Posts are permanent and public. Most judicial conduct codes counsel extreme caution—anything posted should be consistent with the dignity of judicial office and the need for apparent impartiality.' },

  // Legal Reasoning (10)
  { category: 'Legal Reasoning', question_text: 'What is the doctrine of precedent (stare decisis) and how does it operate in common law systems?', existing_answer: 'Stare decisis ("to stand by things decided") requires courts to follow legal principles established in previous decisions (ratio decidendi) by courts of equal or higher authority. This ensures consistency, predictability, and equal treatment. Courts distinguish cases on different facts, disapprove earlier decisions, or await overruling by higher courts. Supreme courts may depart from their own precedents when justice requires. The doctrine balances legal certainty with adaptability to changing circumstances.' },
  { category: 'Legal Reasoning', question_text: 'Explain the difference between ratio decidendi and obiter dicta in judicial decisions.', existing_answer: 'Ratio decidendi ("the reason for deciding") is the binding legal principle necessary for the court\'s decision—the rule of law applied to material facts. It is what courts must follow as precedent. Obiter dicta ("things said by the way") are observations not necessary to the decision—hypothetical reasoning, statements on different facts, or dissenting opinions. Obiter may be persuasive but is not binding. Identifying ratio requires analyzing which propositions were essential to the court\'s conclusion.' },
  { category: 'Legal Reasoning', question_text: 'What is analogical reasoning in law and how do judges apply it?', existing_answer: 'Analogical reasoning involves applying principles from one case to a factually different but relevantly similar situation. Judges identify similarities between the precedent and current case, determine whether differences are material, and extend or limit principles accordingly. The skill lies in identifying legally relevant similarities and distinguishing irrelevant factual differences. Analogical reasoning enables case law to develop incrementally, applying established principles to novel situations while maintaining doctrinal coherence.' },
  { category: 'Legal Reasoning', question_text: 'Describe the various approaches to legal interpretation and their respective advantages.', existing_answer: 'Key interpretive approaches include: (1) Literal rule—apply plain meaning of words; (2) Golden rule—modify literal interpretation to avoid absurd results; (3) Mischief rule (Heydon\'s Case)—identify the problem legislation addressed and interpret to suppress the mischief; (4) Purposive approach—interpret to achieve legislative purpose; (5) Contextual approach—read words in their broader statutory context. Modern courts generally favor purposive interpretation while respecting plain statutory text, with contextual aids used when meaning is ambiguous.' },
  { category: 'Legal Reasoning', question_text: 'What is the role of legal policy in judicial decision-making?', existing_answer: 'Policy considerations shape judicial decisions beyond strict rule-application, particularly in hard cases where rules are ambiguous or competing. Courts consider: consequences of competing interpretations, social utility, economic efficiency, moral considerations, and impact on vulnerable groups. Judges must balance fidelity to law with achieving just outcomes. Explicit policy reasoning (as in Donoghue v. Stevenson) legitimizes judicial development of law but courts must avoid usurping the legislative function.' },
  { category: 'Legal Reasoning', question_text: 'Explain the concept of purposive interpretation and how it differs from literal interpretation.', existing_answer: 'Purposive interpretation construes statutory provisions to achieve the legislator\'s purpose and the statute\'s overall scheme, even if the literal text does not clearly support the result. Unlike literal interpretation (applying plain text meaning), purposive interpretation uses the statute\'s context, preamble, legislative history, and overall purpose. It avoids absurd or unjust results from rigid textual reading while respecting the legislature\'s intent. Modern courts, especially in constitutional interpretation, strongly favor this approach.' },
  { category: 'Legal Reasoning', question_text: 'How do judges approach "hard cases" where the law is uncertain or incomplete?', existing_answer: 'In hard cases, judges employ: (1) careful analysis of existing precedent for analogical guidance, (2) purposive interpretation of relevant legislation, (3) application of general legal principles and maxims, (4) policy analysis of consequences, (5) reference to academic commentary and comparative law. Dworkin argued there is always one right answer found through principled reasoning from the whole legal order. Judges must explain their reasoning transparently, treating hard cases as governed by law, not discretion.' },
  { category: 'Legal Reasoning', question_text: 'What is the relationship between law and morality in legal reasoning?', existing_answer: 'The relationship between law and morality is contested. Natural law theorists hold that law derives its authority from moral principles—unjust laws are not truly laws. Legal positivists (Hart) maintain law is a social fact identifiable without reference to morality—there is no necessary connection. In practice, courts consider moral principles in interpreting legislation, developing common law, and exercising discretion. Constitutional courts frequently engage with fundamental moral values, particularly in rights adjudication.' },
  { category: 'Legal Reasoning', question_text: 'Describe the use of presumptions in statutory interpretation.', existing_answer: 'Presumptions are starting-point rules that apply unless displaced by clear contrary indication in the statute. Common presumptions include: (1) no alteration of common law without express words, (2) statutes do not operate retrospectively, (3) statutes do not bind the Crown without express words, (4) no intention to deprive persons of access to courts, (5) mens rea required for criminal offenses, and (6) consistency with international law. These presumptions guide interpretation and protect fundamental legal values from inadvertent legislative erosion.' },
  { category: 'Legal Reasoning', question_text: 'What is the significance of comparative law in judicial reasoning?', existing_answer: 'Comparative law examines legal systems of other jurisdictions to inform domestic legal development. Courts use foreign decisions as persuasive authority, particularly when: developing nascent areas of law, interpreting constitutional rights (other human rights jurisprudence), or resolving novel questions. Common law courts traditionally cite decisions from other common law jurisdictions. Critics argue foreign authority imports alien values; supporters note shared principles and the universalizing of human rights. Comparative reasoning must always be adapted to domestic constitutional context.' },

  // Statutory Interpretation (10)
  { category: 'Statutory Interpretation', question_text: 'Explain the mischief rule and how it guides interpretation of legislation.', existing_answer: 'The mischief rule, established in Heydon\'s Case (1584), requires courts to identify: (1) the common law before the Act, (2) the mischief or defect the law did not provide for, (3) the remedy Parliament appointed, and (4) the reason for the remedy. Courts interpret the statute to suppress the mischief and advance the remedy. The rule is more purposive than the literal rule and anticipates modern purposive approaches, focusing on what problem the legislature sought to solve.' },
  { category: 'Statutory Interpretation', question_text: 'What is the rule against surplusage in statutory interpretation?', existing_answer: 'The rule against surplusage (ut res magis valeat quam pereat) holds that courts should interpret statutes to give effect to every word; no word should be treated as redundant or superfluous. The legislature is presumed to have chosen its words carefully and deliberately. If one interpretation renders a provision meaningless while another gives it effect, the latter should be preferred. This principle promotes respect for legislative drafting and discourages courts from ignoring statutory text.' },
  { category: 'Statutory Interpretation', question_text: 'Describe the use of explanatory notes and legislative history as aids to statutory interpretation.', existing_answer: 'Explanatory notes (prepared by the promoting department) and legislative history (Hansard debates, committee reports) are extrinsic aids used when statutory language is ambiguous. Following Pepper v. Hart [1993], courts may consult parliamentary debates when: the legislation is ambiguous, the statement was made by a minister or sponsor, and the statement is clear. However, courts must be cautious—debates reflect individual views and may not represent Parliament\'s collective intention; the text remains primary.' },
  { category: 'Statutory Interpretation', question_text: 'What is the ejusdem generis rule and how does it apply in practice?', existing_answer: 'Ejusdem generis ("of the same kind") is a canon of construction holding that general words following specific words in a list are interpreted as referring to things of the same class as the specific words. For example, "cats, dogs, horses, and other animals" would cover domestic animals, not wild ones. The rule prevents general words from being interpreted so broadly that the specific words become redundant. Courts identify the common genus of the specific items and limit general words to that genus.' },
  { category: 'Statutory Interpretation', question_text: 'Explain the principle of expressio unius est exclusio alterius in statutory construction.', existing_answer: 'Expressio unius est exclusio alterius ("the expression of one thing excludes others") holds that explicitly mentioning specific items in a statute implies the exclusion of all others. If a statute lists specific cases to which a rule applies, it implicitly excludes similar cases not listed. While a useful interpretive tool, it must be applied carefully—the presumption of exclusion can be rebutted if context suggests the list was non-exhaustive. Courts avoid applying it mechanically when it would produce absurd results.' },
  { category: 'Statutory Interpretation', question_text: 'How do courts interpret penal statutes and why is the approach distinct?', existing_answer: 'Penal statutes defining criminal offenses are strictly construed in favor of the accused (the principle of strict construction). Ambiguities are resolved in the defendant\'s favor—if a person\'s conduct does not clearly fall within the offense as defined, they should not be convicted. This protects individuals from uncertain criminal liability, upholds the principle nullum crimen sine lege (no crime without law), and maintains the legislature\'s exclusive power to define criminal conduct. Courts will not extend offenses by analogy.' },
  { category: 'Statutory Interpretation', question_text: 'What is the reading-down principle and when is it applied?', existing_answer: 'Reading down is a technique of statutory interpretation giving legislation a narrower meaning than its literal text to make it conform with constitutional requirements or human rights obligations. Instead of striking down legislation, courts apply it in a constitutionally compliant manner. It is applied when: (1) the provision can reasonably bear a narrower interpretation, (2) that interpretation is consistent with Parliament\'s purpose, and (3) no other cure is possible. Reading down respects parliamentary sovereignty while protecting constitutional values.' },
  { category: 'Statutory Interpretation', question_text: 'Describe the internal aids to statutory interpretation.', existing_answer: 'Internal aids are found within the statute itself: (1) Long title—describes the statute\'s general purpose; (2) Short title—identifying name; (3) Preamble—sets out reasons and purpose; (4) Headings and marginal notes—indicate section contents; (5) Definition sections—define key terms for the Act; (6) Schedules—elaboration of main provisions; (7) Other sections—interpreting ambiguous provisions in light of the whole Act (in pari materia). Courts read statutes as a whole, giving individual provisions meaning consistent with the statute\'s overall scheme.' },
  { category: 'Statutory Interpretation', question_text: 'What is the presumption against retrospective legislation and when can it be displaced?', existing_answer: 'Courts presume legislation is prospective (applies to future events) unless Parliament has clearly expressed a retrospective intent, because applying new rules to completed acts is fundamentally unfair and breaches legal certainty. The presumption is strongest for legislation imposing new liabilities or removing accrued rights. It can be displaced by: (1) express language of retrospectivity, (2) necessary implication, or (3) context making retrospective application the only sensible interpretation. Courts apply the presumption strictly for criminal statutes.' },
  { category: 'Statutory Interpretation', question_text: 'Explain how international treaties and conventions influence domestic statutory interpretation.', existing_answer: 'International treaties do not automatically become domestic law but influence interpretation through the presumption of conformity: Parliament is presumed not to legislate contrary to international obligations. When legislation implements a treaty, courts interpret it to conform with treaty obligations. Where ambiguous, courts favor an interpretation consistent with international law. Human rights treaties are especially influential—the Human Rights Act incorporates the ECHR into domestic law in the UK, requiring all legislation to be read compatibly with Convention rights so far as possible.' },

  // Other Judicial Topics (10)
  { category: 'Other Judicial Topics', question_text: 'What is the doctrine of legitimate expectation and how does it operate in judicial review?', existing_answer: 'Legitimate expectation arises when a public authority makes a clear and unequivocal representation (express or implied by established practice) that a person will be treated in a certain way. Courts protect legitimate expectations substantively (preventing contrary action) or procedurally (requiring consultation before departure). The doctrine prevents arbitrary government conduct, upholds good administration, and provides a basis for challenging unexpected policy changes that affect individuals\' reliance on prior assurances.' },
  { category: 'Other Judicial Topics', question_text: 'Describe the Wednesbury unreasonableness standard in administrative law.', existing_answer: 'Wednesbury unreasonableness (from Associated Provincial Picture Houses v. Wednesbury Corporation [1948]) is a ground for judicial review requiring courts to intervene when an administrative decision is "so unreasonable that no reasonable authority could ever have come to it." It represents judicial restraint, deferring to administrative decision-makers on merits while correcting clear irrationality. Modern courts apply a more intensive review (proportionality) for decisions affecting fundamental rights, reserving Wednesbury for purely administrative decisions.' },
  { category: 'Other Judicial Topics', question_text: 'What is access to justice and what are its essential components?', existing_answer: 'Access to justice requires that all persons can effectively use the legal system to vindicate their rights, regardless of financial means, location, or disadvantage. Essential components include: (1) physical access to courts; (2) affordable legal representation (legal aid); (3) comprehensible legal processes; (4) timely resolution; (5) fair hearings; and (6) effective enforcement of judgments. Barriers include cost, complexity, delay, and intimidation. Access to justice is increasingly recognized as a fundamental right and prerequisite for the rule of law.' },
  { category: 'Other Judicial Topics', question_text: 'Explain the concept of judicial activism versus judicial restraint.', existing_answer: 'Judicial activism describes courts taking a creative, expansive approach to interpreting law—developing new principles, giving broad readings to rights, and being willing to depart from precedent or overturn legislation. Judicial restraint involves deferring to the elected legislature and executive, following precedent closely, and avoiding policy judgments. The debate concerns the appropriate role of unelected judges. Activists argue courts must vindicate rights; restraintists argue judicial overreach undermines democratic legitimacy. Most courts occupy a position between these poles.' },
  { category: 'Other Judicial Topics', question_text: 'What is the principle of open justice and why is it fundamental to the legal system?', existing_answer: 'Open justice requires that court proceedings be conducted in public and judgments be available, subject to exceptions. Lord Hewart\'s dictum—"justice must not only be done, but must be seen to be done"—captures the principle. Transparency promotes public confidence, deters judicial misconduct, enables accountability, educates the public about law, and allows scrutiny of the administration of justice. Exceptions (in camera hearings for children, national security) must be strictly justified by necessity, with minimal departure from openness.' },
  { category: 'Other Judicial Topics', question_text: 'Describe the role of international human rights law in domestic court proceedings.', existing_answer: 'International human rights instruments (ICCPR, ECHR, UDHR) increasingly influence domestic legal systems. Where incorporated by legislation, they are directly applicable. Even without incorporation, courts use them as interpretive guides, presuming conformity. Treaty bodies\' decisions inform interpretation of domestic rights. National courts engage with international human rights norms in constitutional interpretation, developing rights-protective approaches. This internationalizing of human rights law raises questions about the relationship between domestic constitutional orders and international legal obligations.' },
  { category: 'Other Judicial Topics', question_text: 'What is the rule of law and what are its essential requirements?', existing_answer: 'The rule of law is the principle that law governs society rather than arbitrary will, whether of individuals or governments. Essential requirements include: (1) law must be prospective, accessible, and clear; (2) laws must apply equally to all including government; (3) individual rights must be protected by independent courts; (4) officials must act within legal authority; (5) courts must be independent; and (6) compliance with international human rights norms. Lord Bingham identified eight components; Dicey emphasized equality before law and supremacy of law.' },
  { category: 'Other Judicial Topics', question_text: 'Explain the concept of proportionality as a standard of review in administrative law.', existing_answer: 'Proportionality requires administrative measures to be: (1) suitable to achieve a legitimate aim; (2) necessary—no less restrictive alternative achieves the aim equally; and (3) proportionate in the strict sense—benefits must outweigh burdens on individual rights. Originating in German and EU law, it is now applied in most rights cases. It requires more intensive scrutiny than Wednesbury, engaging courts in evaluating policy choices when rights are at stake while maintaining deference for complex socio-economic decisions.' },
  { category: 'Other Judicial Topics', question_text: 'What is the significance of the separation of powers doctrine for the independence of the judiciary?', existing_answer: 'Separation of powers ensures the judiciary operates independently from the executive and legislature. Judicial independence requires: security of tenure (judges not removable for their decisions), financial security (salaries not subject to political reduction), and institutional independence (courts control their own procedure). The doctrine protects courts from interference in pending cases, prevents judicial decisions from being legislatively reversed without proper process, and enables courts to hold other branches to constitutional limits without fear of retaliation.' },
  { category: 'Other Judicial Topics', question_text: 'Describe the concept of legal personality and why it matters in law.', existing_answer: 'Legal personality is the attribution of rights, duties, and the capacity to sue and be sued to an entity recognized by law. Natural persons (individuals) have legal personality from birth. Juridical persons (corporations, public authorities, NGOs) are created by law and treated as legal persons distinct from their members. Legal personality enables entities to: hold property, enter contracts, and litigate. It creates limited liability for shareholders. Courts have extended personality questions to issues of corporate liability, human rights claims, and the rights of future generations.' },
];

async function seed() {
  console.log(`Seeding ${questions.length} legal questions...`);
  
  // Use Supabase REST API directly via fetch
  const res = await fetch(`${supabaseUrl}/rest/v1/questions`, {
    method: 'POST',
    headers: {
      'apikey': supabaseKey,
      'Authorization': `Bearer ${supabaseKey}`,
      'Content-Type': 'application/json',
      'Prefer': 'return=minimal'
    },
    body: JSON.stringify(questions.map(q => ({
      question_text: q.question_text,
      existing_answer: q.existing_answer,
      category: q.category,
      status: 'available'
    })))
  });

  if (!res.ok) {
    const err = await res.text();
    console.error('Error seeding questions:', err);
    process.exit(1);
  }

  console.log(`✅ Successfully seeded ${questions.length} legal questions into Supabase!`);
}

seed();
